#pragma once
#include <string>
#include <DiscordPP/JSON.hpp>
#include <DiscordPP/IDiscordObject.h>
#include "JSON.hpp"

enum EPayloadType
{
	HANDSHAKE,
	READY,
	RESUME,
	CHANNEL_CREATE,
	CHANNEL_UPDATE,
	CHANNEL_DELETE,
	GUILD_CREATE,
	GUILD_DELETE,
	GUILD_BAN_ADD,
	GUILD_BAN_REMOVE,
	GUILD_EMOJI_UPDATE,
	GUILD_INTEGRATIONS_UPDATE,
	GUILD_MEMBER_ADD,
	GUILD_MEMBER_REMOVE,
	GUILD_MEMBER_UPDATE,
	GUILD_MEMBERS_CHUNK,
	GUILD_ROLE_CREATE,
	GUILD_ROLE_UPDATE,
	GUILD_ROLE_DELETE,
	MESSAGE_CREATE,
	MESSAGE_UPDATE,
	MESSAGE_DELETE,
	MESSAGE_DELETE_BULK,
	PRECENSE_UPDATE,
	TYPING_START,
	USER_SETTINGS_UPDATE,
	USER_UPDATE,
	VOICE_STATE_UPDATE,
	VOICE_SERVER_UPDATE
};

struct SEventParams
{
	std::string raw;
	int opCode;
	EPayloadType type;
	nlohmann::json object;
};